
###
GET http://localhost:3000/clientes

###
GET http://localhost:3000/clientes/6

###
POST http://localhost:3000/clientes/
Content-Type: application/json

{
    "nombre":"Diana Cortes",
    "direccion": "cra 80 n 67 4",
    "telefono": "3866757",
    "correo_electronico":"diana@gmail.com"
}

###
PUT http://localhost:3000/clientes/4
Content-Type: application/json

{
    "Correo_electronico":"fernando@gmail.com"
}

###
DELETE http://localhost:3000/clientes/5
